// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg7UzUhC1y3zDz15Hm7g3FBt9IIMHtl48',
    appId: '1:938717166926:web:fec85a40db11621f8cb21f',
    messagingSenderId: '938717166926',
    projectId: 'level-up-life-800e4',
    authDomain: 'level-up-life-800e4.firebaseapp.com',
    storageBucket: 'level-up-life-800e4.firebasestorage.app',
    measurementId: 'G-EPZ1FTZ3G8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDScC0ZfYxL3a6rOTeziLgYGVawE_GPBsA',
    appId: '1:938717166926:android:15ba91bbe95093ac8cb21f',
    messagingSenderId: '938717166926',
    projectId: 'level-up-life-800e4',
    storageBucket: 'level-up-life-800e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRiLZlp29SPlf21hvsBsBE_X6Yshld2U4',
    appId: '1:938717166926:ios:3a8402e95333d2ff8cb21f',
    messagingSenderId: '938717166926',
    projectId: 'level-up-life-800e4',
    storageBucket: 'level-up-life-800e4.firebasestorage.app',
    iosBundleId: 'com.example.levelUpLife',
  );

}